import { Col, Row } from 'antd'
import React from 'react'
import { Container } from 'react-bootstrap'

const Privacy = () => {
  return (
    <main>
      <section className='py-5 sm:px-0 md:px-0 lg:px-32'>
        <Container>
          <Row>
            <Col span={24} className='text-center'>
              <div className='text-black text-3xl sm:text-5xl font-semibold text-center w-2/3 mx-auto'>Privacy Policy</div>
            </Col>
            <Col span={24}>
                <ul className='list-decimal space-y-2' >
                  <li className='text-2xl font-bold pb-2'>Introduction</li>
                  <p className='fs-6 text-justify'> Welcome to KnowledegeNest COMPUTER EDUCATION <br /> KnowledegeNest COMPUTER EDUCATION (“us”, “we”, or “our”) operates (hereinafter referred to as “Service”).
                    Our Privacy Policy governs your visit to , and explains how we collect, safeguard and disclose information that results from your use of our Service. <br />We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions. <br /> Our Terms and Conditions <b> (“Terms” )</b> govern all use of our Service and together with the Privacy Policy constitutes your agreement with us <b> (“agreement”) </b>.</p>
                  <li className='text-2xl font-bold py-2'> Definitions</li>
                  <p className='fs-6 text-justify space-y-2'> <b>SERVICE</b> means the https://stpcomputereducation.com website operated by KnowledegeNest COMPUTER EDUCATION.
                    <br /> <b>PERSONAL DATA</b> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
                    <br /> <b>USAGE DATA</b> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).
                    <br />COOKIES are small files stored on your device ( computer or mobile device).
                    <br /><b>DATA CONTROLLER</b> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.
                    <br /> <b>DATA PROCESSORS (OR SERVICE PROVIDERS)</b> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
                    <br /> <b>DATA SUBJECT</b> is any living individual who is the subject of Personal Data.
                    <br /> <b>THE USER </b>is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
                  </p>
                  <li className='text-2xl font-bold py-2'> Information Collection and Use</li>
                  <p className='fs-6 text-justify space-y-2'>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
                  <li className='text-2xl font-bold py-2'> Types of Data Collected</li>
                  <div className='fs-6 text-justify space-y-2'>
                    <p className='font-bold fs-5 py-2'>Personal Data</p>
                    <p className='fs-6 text-justify space-y-2'>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you <b>(“Personal Data”)</b>. Personally identifiable information may include, but is not limited to:</p>
                    <ul className='list-disc ms-3'>
                      <li>Email address</li>
                      <li>First name and last name</li>
                      <li>Phone number</li>
                      <li>Address, Country, State, Province, ZIP/Postal code, City</li>
                      <li> Cookies and Usage Data</li>
                    </ul>
                    <p className='fs-6 text-justify space-y-2'>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.</p>
                    <p className='font-bold fs-5 py-2'>Usage Data</p>
                    <p className='fs-6 text-justify space-y-2'>We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device <b>(“Usage Data”)</b>.
                      This Usage Data may include information such as your  computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                      When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.</p>
                    <p className='font-bold fs-5 py-2'>Location Data</p>
                    <p className='fs-6 text-justify space-y-2'>We may use and store information about your location if you give us permission to do so <b>(“Location Data”)</b>. We use this data to provide features of our Service, to improve and customize our Service.
                      You can enable or disable location services when you use our Service at any time by way of your device settings.</p>
                    <div className='fs-6 text-justify space-y-2'>
                      <p className='font-bold fs-5 py-2'>Tracking Cookies Data</p>
                      <p className='fs-6 text-justify space-y-2'>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
                        Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.
                        You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service. <br /> Examples of Cookies we use:</p>
                      <ul className='list-disc ms-3'>
                        <li> <b>Session Cookies:</b> We use Session Cookies to operate our Service.</li>
                        <li> <b>Preference Cookies:</b> We use Preference Cookies to remember your preferences and various settings.</li>
                        <li> <b>Security Cookies:</b> We use Security Cookies for security purposes.</li>
                        <li> <b>Advertising Cookies:</b> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests</li>
                      </ul>
                      <p className='font-bold fs-5 py-2'>Other Data</p>
                      <p className='fs-6 text-justify space-y-2'>While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, non-disclosure agreements, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location and other data.</p>
                    </div>
                    <li className='text-2xl font-bold py-2'> Use of Data</li>
                    <div className='fs-6 text-justify space-y-2'>
                      <p>KnowledegeNest COMPUTER EDUCATION uses the collected data for various purposes:</p>
                      <ul className='list-disc ms-3'>
                        <li> to provide and maintain our Service;</li>
                        <li> to notify you about changes to our Service;</li>
                        <li>to allow you to participate in interactive features of our Service when you choose to do so;</li>
                        <li>to provide customer support;</li>
                        <li>to gather analysis or valuable information so that we can improve our Service;</li>
                        <li> to monitor the usage of our Service;</li>
                        <li> to detect, prevent and address technical issues;</li>
                        <li>to fulfil any other purpose for which you provide it;</li>
                        <li> to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</li>
                        <li>to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</li>
                        <li>to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
                        <li>in any other way we may describe when you provide the information;</li>
                        <li>for any other purpose with your consent.</li>
                      </ul>
                    </div>
                    <li className='text-2xl font-bold py-2'> Retention of Data</li>
                    <p className='fs-6 text-justify space-y-2'>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                    <p className='fs-6 text-justify space-y-2'>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
                    <li className='text-2xl font-bold py-2'> Transfer of Data</li>
                    <p className='fs-6 text-justify space-y-2'>Your information, including Personal Data, may be transferred to – and maintained on –  computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
                      If you are located outside PAKISTAN and choose to provide information to us, please note that we transfer the data, including Personal Data, to PAKISTAN and process it there.</p>
                    <p className='fs-6 text-justify space-y-2'>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
                      kNOWLEDEGENEST COMPUTER EDUCATION will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
                    <li className='text-2xl font-bold py-2'>Security of Data</li>
                    <p className='fs-6 text-justify space-y-2'>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
                    <li className='text-2xl font-bold py-2'>Service Providers</li>
                    <p className='fs-6 text-justify space-y-2'>We may employ third party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.
                      These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
                    <li className='text-2xl font-bold py-2'>Contact Us</li>
                    <p className='fs-6 text-justify px-2'>If you have any questions about this Privacy Policy, please contact us by Phone Number </p>

                  </div>
                </ul>
            </Col>
          </Row>
        </Container>
      </section>
    </main>
  )
}

export default Privacy